# -*- coding: utf-8 -*-
"""shannon-nyquist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrWQ-d-wkfkvCnTX6grWVn6lpai5unHP
"""

import matplotlib
import matplotlib.pyplot as plt
from matplotlib import rc

import numpy as np

plt.rc('text', usetex=True)
plt.rc('text.latex', preamble=r'\usepackage{amsmath} \usepackage{amsmath} \usepackage{amssymb}')
matplotlib.rc('font', **{'family': 'sans serif', 'serif': ['Computer Modern'], 'size': 8})

# matplotlib.rc('xtick', labelsize=8)
# matplotlib.rc('ytick', labelsize=8)
#
# matplotlib.rc('text', usetex=True)
#
# matplotlib.rcParams['text.latex.preamble'] = [
#     r'\usepackage{amsfonts}',
#     r'',
#     r''
# ]

########################################
# Parameters
########################################

# Number of elements
ris_num_els_ver_range = np.arange(1, 1001)

# Size of each element
fundamental_freq_range = np.array([1/4, 1/2, 1])

# Compute lower bound
lower_bound = np.zeros((fundamental_freq_range.size, ris_num_els_ver_range.size))

# Go through all frequencies
for ii, fundamental_freq in enumerate(fundamental_freq_range):

    # Compute bound
    lower_bound[ii, :] = np.ceil(2 * np.pi * ris_num_els_ver_range * fundamental_freq)

########################################
# PLot signal
########################################
fig, ax = plt.subplots(figsize=(3.15, 3))

styles = ['-', '--', ':']
labels = ['0.25', '0.5', '1']

# Go through all frequencies
for ii, fundamental_freq in enumerate(fundamental_freq_range):
    ax.plot(ris_num_els_ver_range, lower_bound[ii, :], linestyle=styles[ii], color='black', linewidth=1.5, label='$F_0=' + str(labels[ii]) + '$ Hz')

ax.set_xlabel(r'number of vertical elements, $M_x$')
ax.set_ylabel(r'$N_{\rm ce}$ lower bound')

ax.set_xscale('log')
ax.set_yscale('log')

ax.legend(fontsize='x-small', framealpha=0.5)

ax.grid(color='gray', linestyle=':', linewidth=0.5, alpha=0.5)

plt.tight_layout()

plt.show()
